/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_meneguzzi_jemplan_EMPlan */

#ifndef _Included_org_meneguzzi_jemplan_EMPlan
#define _Included_org_meneguzzi_jemplan_EMPlan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_meneguzzi_jemplan_EMPlan
 * Method:    emplan
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_meneguzzi_jemplan_EMPlan_emplan
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_meneguzzi_jemplan_EMPlan
 * Method:    emplanStream
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_meneguzzi_jemplan_EMPlan_emplanStream
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
